;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Ability.VoidJourney",NewTagName="Ability.VoidPhase")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Void.Peek",DevComment="")
+GameplayTagList=(Tag="Ability.Void.Phase",DevComment="")
+GameplayTagList=(Tag="Cooldown.Void.Peek",DevComment="")
+GameplayTagList=(Tag="Cooldown.Void.Phase",DevComment="")
+GameplayTagList=(Tag="Event.Void.Phase.MarkPlaced",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Void.Peek.Scan",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Void.Phase.Exit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Void.Phase.Travel",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Void.Phase.Windup",DevComment="")
+GameplayTagList=(Tag="State.Phasing",DevComment="")
+GameplayTagList=(Tag="State.Windup",DevComment="")

